package cli

import (
	"errors"
	"flag"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"
)

const starterYAML = `# Generated by webhook init. Set WEBHOOK_SECRET and run with -template.
- id: hello
  execute-command: /bin/echo
  response-message: accepted
  http-methods:
    - POST
  pass-arguments-to-command:
    - source: string
      name: webhook received
  trigger-rule:
    match:
      type: payload-hmac-sha256
      secret: '{{ getenv "WEBHOOK_SECRET" }}'
      parameter:
        source: header
        name: X-Hub-Signature-256
`

const starterJSON = `[
  {
    "id": "hello",
    "execute-command": "/bin/echo",
    "response-message": "accepted",
    "http-methods": ["POST"],
    "pass-arguments-to-command": [
      {"source": "string", "name": "webhook received"}
    ],
    "trigger-rule": {
      "match": {
        "type": "payload-hmac-sha256",
        "secret": "{{ getenv ` + "`WEBHOOK_SECRET`" + ` }}",
        "parameter": {"source": "header", "name": "X-Hub-Signature-256"}
      }
    }
  }
]
`

// Normalize converts the developer-friendly subcommands into the legacy flags
// understood by the existing parser. The legacy interface remains supported.
func Normalize(args []string) (normalized []string) {
	if len(args) == 0 {
		return args
	}

	switch args[0] {
	case "validate":
		normalized = []string{"-validate-config"}
	case "doctor":
		normalized = []string{"-doctor"}
	default:
		return args
	}

	for _, arg := range args[1:] {
		if arg == "--strict" || arg == "-strict" {
			normalized = append(normalized, "-validate-strict")
			continue
		}
		normalized = append(normalized, arg)
	}
	return normalized
}

// IsInit reports whether args select the init subcommand.
func IsInit(args []string) bool {
	return len(args) > 0 && args[0] == "init"
}

// RunInit writes a secure starter hook configuration.
func RunInit(args []string, stdout, stderr io.Writer) int {
	fs := flag.NewFlagSet("webhook init", flag.ContinueOnError)
	fs.SetOutput(stderr)
	output := fs.String("output", "", "path for the generated hook configuration")
	format := fs.String("format", "yaml", "configuration format: yaml or json")
	force := fs.Bool("force", false, "overwrite an existing file")
	if err := fs.Parse(args); err != nil {
		return 2
	}

	var data string
	switch strings.ToLower(strings.TrimSpace(*format)) {
	case "yaml", "yml":
		data = starterYAML
		if strings.TrimSpace(*output) == "" {
			*output = filepath.Join("hooks", "hooks.yaml")
		}
	case "json":
		data = starterJSON
		if strings.TrimSpace(*output) == "" {
			*output = filepath.Join("hooks", "hooks.json")
		}
	default:
		fmt.Fprintf(stderr, "unsupported format %q; use yaml or json\n", *format)
		return 2
	}
	cleanOutput := filepath.Clean(*output)
	if !*force {
		if _, err := os.Stat(cleanOutput); err == nil {
			fmt.Fprintf(stderr, "%s already exists; use --force to overwrite it\n", cleanOutput)
			return 1
		} else if !errors.Is(err, os.ErrNotExist) {
			fmt.Fprintf(stderr, "cannot inspect %s: %v\n", cleanOutput, err)
			return 1
		}
	}
	if err := os.MkdirAll(filepath.Dir(cleanOutput), 0o750); err != nil {
		fmt.Fprintf(stderr, "cannot create output directory: %v\n", err)
		return 1
	}
	flags := os.O_WRONLY | os.O_CREATE
	if *force {
		flags |= os.O_TRUNC
	} else {
		flags |= os.O_EXCL
	}
	file, err := os.OpenFile(cleanOutput, flags, 0o600)
	if err != nil {
		fmt.Fprintf(stderr, "cannot create %s: %v\n", cleanOutput, err)
		return 1
	}
	if _, err := io.WriteString(file, data); err != nil {
		_ = file.Close()
		fmt.Fprintf(stderr, "cannot write %s: %v\n", cleanOutput, err)
		return 1
	}
	if err := file.Close(); err != nil {
		fmt.Fprintf(stderr, "cannot close %s: %v\n", cleanOutput, err)
		return 1
	}

	fmt.Fprintf(stdout, "Created %s\n", cleanOutput)
	fmt.Fprintln(stdout, "Next: set WEBHOOK_SECRET, then run webhook validate --strict -template -hooks "+cleanOutput)
	return 0
}
