FROM alpine:3.19.0 as builder
RUN apk --update add ca-certificates upx
RUN upx -9 -o webhook.minify webhook && \
    chmod +x webhook.minify

FROM scratch
LABEL maintainer "soulteary <soulteary@gmail.com>"
COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt
COPY webhook.minify /usr/bin/webhook
EXPOSE 8345/tcp
CMD ["/usr/bin/webhook"]